experiment:
  name: default_exp

models:
  user_model:
    model_path: "deepseek-chat"
    api_key: "sk-785db80201014ade891d1db0525e48fd"
    base_url: "https://api.deepseek.com"
    vllmapi: true
  assistant_model:
    model_path: "deepseek-chat"
    api_key: "sk-785db80201014ade891d1db0525e48fd"
    base_url: "https://api.deepseek.com"
    vllmapi: true
  analysis_model:
    model_path: "deepseek-chat"
    api_key: "sk-785db80201014ade891d1db0525e48fd"
    base_url: "https://api.deepseek.com"
    vllmapi: true

retriever:
  embedding_model_path: "/remote-home/share/fyduan_share/MODELS/Qwen3-Embedding-0.6B"
  max_length: 512
  embedding_dim: 1024
  persist_directory: "./chromadb"
  device: "cpu"
  logger_silent: false

paths:
  events_path: "./event_sequences/events.jsonl"
  users_path: "./event_sequences/users.jsonl"
  preference_file: "./language_templates.json"

simulator:
  alpha: 0.5